### ISSUE TITLE
Signficant difference in tessellated fills

### ISSUE THREAD

**Issue by jonahwilliams** [jonahwilliams/svg_2#10]
![image](https://user-images.githubusercontent.com/8975114/155386706-95e94aa5-2987-4408-aefd-5bfd6a643c37.png)

![image](https://user-images.githubusercontent.com/8975114/155386732-9cd48706-b439-453a-a3e2-47544c2c5728.png)

**Comment by dnfield** [comment]
I created a unit test in impeller and used SkPathUtils::FromSVGString, and get this:

<img width="366" alt="image" src="https://user-images.githubusercontent.com/8620741/155396194-ed8f7078-6ac7-40ce-ae38-7dec203bfb6e.png">


I do also see warnings though in the output about 

```
[ERROR:flutter/impeller/base/validation.cc(14)] Zero index count in render pass command.
[ERROR:flutter/impeller/base/validation.cc(24)] Break on ImpellerValidationBreak to inspect point of failure.
```

**Comment by dnfield** [comment]
There's some strange rendering artifact on the right side under the top of the darker blue hill.

**Comment by dnfield** [comment]
Opened https://github.com/flutter/impeller/pull/24 to track the impeller related bugs here.

**Comment by jonahwilliams** [comment]
with x1/y1 swapped with x3/y3

![image](https://user-images.githubusercontent.com/8975114/155601510-aa8b4961-e7ae-48bb-a196-5e2754af6bdb.png)

**Comment by dnfield** [comment]
There's still some issues with moveTo in impeller

**Comment by dnfield** [comment]
Have confirmed that with flutter/impeller#32 this all looks as expected. Will want to make sure something funky isn't going on with Windows though

![image](https://user-images.githubusercontent.com/8620741/155685567-4d783fbf-b0eb-4969-a70b-2f2abb1dc5b7.png)

**Comment by dnfield** [comment]
Also was tested against patch in #11

**Comment by jonahwilliams** [comment]
New results:

![image](https://user-images.githubusercontent.com/8975114/155771441-3c4faa82-4e1b-41c3-a9fc-2240c502711c.png)

Looks fixed! We could probably do with some AA/smoothing or something like that
